[package]
name = "syntropy-tunnel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
syntropy-proto = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["tls", "tls-roots"] }
prost = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
