#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Syntropy GCP 3-User MicroVM Host Setup"

# ── Stage 1: GCP Project & Zone ──────────────────────────────────────────
stage "GCP Project & Zone Configuration"
say "Configure the target Google Cloud Project and compute zone."
say "Ensure your chosen zone supports Intel Cascade Lake (e.g., us-central1-a, us-east4-a)."

open_url "https://console.cloud.google.com/projectselector2/home/dashboard"
step "In Google Cloud Console, select or create your project."
step "Copy the Project ID (e.g. 'syntropy-cloud-prod')."

DEFAULT_PROJECT=""
if command -v gcloud >/dev/null 2>&1; then
  DEFAULT_PROJECT=$(gcloud config get-value project 2>/dev/null || true)
fi

ask GCP_PROJECT_ID "Enter GCP Project ID:"
if [[ -z "$GCP_PROJECT_ID" && -n "$DEFAULT_PROJECT" ]]; then
  GCP_PROJECT_ID="$DEFAULT_PROJECT"
fi

if [[ -z "$GCP_PROJECT_ID" ]]; then
  warn "Project ID cannot be empty. Please enter a valid GCP Project ID."
  ask GCP_PROJECT_ID "Enter GCP Project ID:"
fi

write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

step "Choose a GCP zone with Intel Cascade Lake availability."
note "Recommended default: us-central1-a"
ask GCP_ZONE "Enter GCP Zone [default: us-central1-a]:"
GCP_ZONE="${GCP_ZONE:-us-central1-a}"
write_env GCP_ZONE "$GCP_ZONE"

if command -v gcloud >/dev/null 2>&1; then
  if confirm "Configure active gcloud CLI project & zone now?"; then
    gcloud config set project "$GCP_PROJECT_ID" 2>/dev/null || true
    gcloud config set compute/zone "$GCP_ZONE" 2>/dev/null || true
    say "✓ gcloud CLI active config updated."
  fi
fi

# ── Stage 2: Enable GCP APIs ──────────────────────────────────────────────
stage "Enable Required Google Cloud APIs"
say "Syntropy requires Compute Engine, Cloud Storage, and Secret Manager APIs."

open_url "https://console.cloud.google.com/flows/enableapi?apiid=compute.googleapis.com,storage.googleapis.com,secretmanager.googleapis.com&project=${GCP_PROJECT_ID}"
step "In the browser, click 'ENABLE' to enable the required service APIs."

if command -v gcloud >/dev/null 2>&1; then
  if confirm "Enable these APIs via gcloud CLI now?"; then
    say "Enabling APIs: compute, storage, secretmanager..."
    gcloud services enable \
      compute.googleapis.com \
      storage.googleapis.com \
      secretmanager.googleapis.com \
      --project="$GCP_PROJECT_ID"
    say "✓ APIs enabled successfully."
  fi
else
  pause "Press Enter once the APIs are enabled in the Cloud Console..."
fi

# ── Stage 3: Cloud Storage /agent-store Bucket ─────────────────────────────
stage "Cloud Storage /agent-store FUSE Bucket"
say "Each agent microVM shares persistent worktrees via the /agent-store FUSE backing."
say "We will create or associate a Google Cloud Storage bucket for this store."

DEFAULT_BUCKET="syntropy-agent-store-${GCP_PROJECT_ID}"
step "Choose a globally unique GCS bucket name."
note "Suggested: ${DEFAULT_BUCKET}"
ask AGENT_STORE_BUCKET "Enter Bucket Name [default: ${DEFAULT_BUCKET}]:"
AGENT_STORE_BUCKET="${AGENT_STORE_BUCKET:-$DEFAULT_BUCKET}"
write_env AGENT_STORE_BUCKET "$AGENT_STORE_BUCKET"

if command -v gcloud >/dev/null 2>&1; then
  if confirm "Create bucket gs://${AGENT_STORE_BUCKET} automatically now?"; then
    if gcloud storage buckets describe "gs://${AGENT_STORE_BUCKET}" --project="$GCP_PROJECT_ID" >/dev/null 2>&1; then
      say "✓ Bucket gs://${AGENT_STORE_BUCKET} already exists."
    else
      gcloud storage buckets create "gs://${AGENT_STORE_BUCKET}" \
        --project="$GCP_PROJECT_ID" \
        --location="US" \
        --uniform-bucket-level-access
      say "✓ Created bucket gs://${AGENT_STORE_BUCKET}."
    fi
  fi
else
  open_url "https://console.cloud.google.com/storage/browser?project=${GCP_PROJECT_ID}"
  step "Create bucket 'gs://${AGENT_STORE_BUCKET}' in Google Cloud Console."
  pause "Press Enter once the bucket is created..."
fi

# ── Stage 4: 3-User Authorized IP Firewall ────────────────────────────────
stage "3-User Authorized IP Firewall Rule"
say "Syntropy isolates cloud microVMs with strict ingress firewall rules."
say "Allowed ports: 3000 (Console), 6080 (User 1 noVNC), 6081 (Fork Mux), 50051 (gRPC), 22 (SSH)."

DETECTED_IP=""
if command -v curl >/dev/null 2>&1; then
  DETECTED_IP=$(curl -s --max-time 3 https://ifconfig.me || curl -s --max-time 3 https://api.ipify.org || true)
fi

step "Provide comma-separated public IPs or CIDR blocks for the 3 authorized users."
if [[ -n "$DETECTED_IP" ]]; then
  note "Detected your current public IP: ${DETECTED_IP}/32"
  ask ALLOWED_SOURCE_IPS "Enter allowed source IPs/CIDRs [default: ${DETECTED_IP}/32]:"
  ALLOWED_SOURCE_IPS="${ALLOWED_SOURCE_IPS:-${DETECTED_IP}/32}"
else
  ask ALLOWED_SOURCE_IPS "Enter allowed source IPs/CIDRs (e.g. 1.2.3.4/32,5.6.7.8/32):"
fi

write_env ALLOWED_SOURCE_IPS "$ALLOWED_SOURCE_IPS"

FW_RULE_NAME="allow-syntropy-3users"
if command -v gcloud >/dev/null 2>&1; then
  if confirm "Create firewall rule '${FW_RULE_NAME}' in GCP now?"; then
    if gcloud compute firewall-rules describe "$FW_RULE_NAME" --project="$GCP_PROJECT_ID" >/dev/null 2>&1; then
      say "Updating existing firewall rule '${FW_RULE_NAME}'..."
      gcloud compute firewall-rules update "$FW_RULE_NAME" \
        --project="$GCP_PROJECT_ID" \
        --source-ranges="$ALLOWED_SOURCE_IPS"
    else
      say "Creating firewall rule '${FW_RULE_NAME}'..."
      gcloud compute firewall-rules create "$FW_RULE_NAME" \
        --project="$GCP_PROJECT_ID" \
        --allow=tcp:22,tcp:3000,tcp:6080,tcp:6081,tcp:50051 \
        --target-tags="syntropy-host" \
        --source-ranges="$ALLOWED_SOURCE_IPS" \
        --description="Authorized access for 3 Syntropy users (Console, noVNC, gRPC, SSH)"
    fi
    say "✓ Firewall rule configured."
  fi
else
  open_url "https://console.cloud.google.com/net-security/firewall-manager/firewall-policies/list?project=${GCP_PROJECT_ID}"
  step "Create a firewall rule '${FW_RULE_NAME}' allowing tcp:22,3000,6080,6081,50051 for tag 'syntropy-host' from ${ALLOWED_SOURCE_IPS}."
  pause "Press Enter once firewall rule is created..."
fi

# ── Stage 5: Nested KVM Compute Engine Host ───────────────────────────────
stage "Provision Nested-KVM Compute Engine Host"
say "We will provision an n2-standard-16 instance with Intel Cascade Lake and nested KVM."
say "This provides 16 vCPUs and 64 GB RAM, enabling 3 concurrent MicroVMs (4 vCPUs / 16 GB each)."

DEFAULT_INSTANCE="syntropy-host-01"
ask GCP_INSTANCE_NAME "Enter host instance name [default: ${DEFAULT_INSTANCE}]:"
GCP_INSTANCE_NAME="${GCP_INSTANCE_NAME:-$DEFAULT_INSTANCE}"
write_env GCP_INSTANCE_NAME "$GCP_INSTANCE_NAME"

MACHINE_TYPE="n2-standard-16"
BOOT_DISK_SIZE="200GB"

STARTUP_SCRIPT=$(cat << 'EOF'
#!/bin/bash
set -euo pipefail
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils cpu-checker \
  xvfb x11vnc openbox websockify novnc curl git build-essential pkg-config libssl-dev

modprobe kvm_intel || true
usermod -aG kvm ubuntu || true

# Install Firecracker v1.10.1
ARCH="$(uname -m)"
FC_VER="v1.10.1"
curl -sL "https://github.com/firecracker-microvm/firecracker/releases/download/${FC_VER}/firecracker-${FC_VER}-${ARCH}.tgz" -o /tmp/fc.tgz
tar -xzf /tmp/fc.tgz -C /usr/local/bin --strip-components=1 "release-${FC_VER}-${ARCH}/firecracker-${FC_VER}-${ARCH}"
ln -sf "/usr/local/bin/firecracker-${FC_VER}-${ARCH}" /usr/local/bin/firecracker
rm -f /tmp/fc.tgz

echo "[✓] Syntropy Host dependencies installed" > /var/log/syntropy-bootstrap.log
EOF
)

if command -v gcloud >/dev/null 2>&1; then
  if confirm "Create Compute Engine instance '${GCP_INSTANCE_NAME}' via gcloud now?"; then
    say "Deploying ${MACHINE_TYPE} instance with nested virtualization in ${GCP_ZONE}..."
    gcloud compute instances create "${GCP_INSTANCE_NAME}" \
      --project="${GCP_PROJECT_ID}" \
      --zone="${GCP_ZONE}" \
      --machine-type="${MACHINE_TYPE}" \
      --min-cpu-platform="Intel Cascade Lake" \
      --enable-nested-virtualization \
      --image-family="ubuntu-2404-lts-amd64" \
      --image-project="ubuntu-os-cloud" \
      --boot-disk-size="${BOOT_DISK_SIZE}" \
      --boot-disk-type="pd-ssd" \
      --tags="syntropy-host" \
      --scopes="cloud-platform" \
      --metadata=startup-script="$STARTUP_SCRIPT"

    say "Retrieving instance external IP..."
    VM_EXTERNAL_IP=$(gcloud compute instances describe "${GCP_INSTANCE_NAME}" \
      --project="${GCP_PROJECT_ID}" \
      --zone="${GCP_ZONE}" \
      --format='get(networkInterfaces[0].accessConfigs[0].natIP)' 2>/dev/null || true)
    say "✓ Instance provisioned with external IP: ${VM_EXTERNAL_IP}"
  fi
fi

if [[ -z "${VM_EXTERNAL_IP:-}" ]]; then
  open_url "https://console.cloud.google.com/compute/instances?project=${GCP_PROJECT_ID}"
  step "If created manually or gcloud wasn't run, check the external IP in Google Cloud Console."
  ask VM_EXTERNAL_IP "Enter host VM External IP address:"
fi
write_env VM_EXTERNAL_IP "$VM_EXTERNAL_IP"

# ── Stage 6: 3-User Account & Display Allocation ──────────────────────────
stage "3-User Account & Display Allocation"
say "Allocate dedicated displays, tokens, and isolation slices for the 3 users."

step "Enter identifiers for the 3 concurrent users."
ask USER_1_EMAIL "Enter User 1 identifier/email [default: user1@example.com]:"
USER_1_EMAIL="${USER_1_EMAIL:-user1@example.com}"
write_env USER_1_EMAIL "$USER_1_EMAIL"

ask USER_2_EMAIL "Enter User 2 identifier/email [default: user2@example.com]:"
USER_2_EMAIL="${USER_2_EMAIL:-user2@example.com}"
write_env USER_2_EMAIL "$USER_2_EMAIL"

ask USER_3_EMAIL "Enter User 3 identifier/email [default: user3@example.com]:"
USER_3_EMAIL="${USER_3_EMAIL:-user3@example.com}"
write_env USER_3_EMAIL "$USER_3_EMAIL"

USER_1_VNC="http://${VM_EXTERNAL_IP}:6080/vnc.html?autoconnect=true&resize=remote"
USER_2_VNC="http://${VM_EXTERNAL_IP}:6081/vnc.html?token=user2&autoconnect=true&resize=remote"
USER_3_VNC="http://${VM_EXTERNAL_IP}:6081/vnc.html?token=user3&autoconnect=true&resize=remote"
CONSOLE_URL="http://${VM_EXTERNAL_IP}:3000"

write_env USER_1_VNC_URL "$USER_1_VNC"
write_env USER_2_VNC_URL "$USER_2_VNC"
write_env USER_3_VNC_URL "$USER_3_VNC"
write_env SYNTROPY_CONSOLE_URL "$CONSOLE_URL"

say "Display Mapping Configured:"
say "  • User 1 (${USER_1_EMAIL}): Display :1 (RFB 5901) → Port 6080 (Primary)"
say "  • User 2 (${USER_2_EMAIL}): Display :2 (RFB 5902) → Port 6081 (Token: user2)"
say "  • User 3 (${USER_3_EMAIL}): Display :3 (RFB 5903) → Port 6081 (Token: user3)"
pause "Press Enter to proceed to deployment and service startup..."

# ── Stage 7: Host Deployment & Verification ───────────────────────────────
stage "Host Deployment & Verification"
say "We will bootstrap the 3-user display multiplexer and Syntropy Web Console on the VM."

REMOTE_SETUP_SCRIPT=$(cat << 'EOF'
#!/usr/bin/env bash
set -euo pipefail

TOKEN_DIR="/tmp/sand-novnc-tokens.d"
LOG_DIR="/tmp/syntropy-display-logs"
mkdir -p "${TOKEN_DIR}" "${LOG_DIR}" /tmp/.X11-unix
chmod 1777 /tmp/.X11-unix "${TOKEN_DIR}"

pkill -f websockify || true
pkill -f Xvfb || true
pkill -f x11vnc || true

websockify --web=/usr/share/novnc --heartbeat=30 0.0.0.0:6080 127.0.0.1:5901 > "${LOG_DIR}/websockify_primary.log" 2>&1 &
websockify --web=/usr/share/novnc --heartbeat=30 --token-plugin TokenFile --token-source "${TOKEN_DIR}" 0.0.0.0:6081 > "${LOG_DIR}/websockify_forks.log" 2>&1 &

spawn_display() {
  local D="$1"
  local RFB=$((5900 + D))
  local TOKEN="$2"

  Xvfb ":${D}" -screen 0 1280x800x24 -ac +extension GLX +render -noreset > "${LOG_DIR}/xvfb_${D}.log" 2>&1 &
  sleep 0.5
  DISPLAY=":${D}" openbox > /dev/null 2>&1 &
  x11vnc -skip_lockkeys -display ":${D}" -localhost -nopw -shared -forever -noxdamage -rfbport "${RFB}" -quiet > "${LOG_DIR}/x11vnc_${D}.log" 2>&1 &
  
  if [[ -n "$TOKEN" ]]; then
    echo "${TOKEN}: 127.0.0.1:${RFB}" > "${TOKEN_DIR}/${TOKEN}.token"
  fi
}

spawn_display 1 ""
spawn_display 2 "user2"
spawn_display 3 "user3"

echo "[✓] All 3 displays running and mapped to noVNC ports 6080/6081."
EOF
)

say "To launch the multi-user displays on your GCP VM, execute the following command:"
step "Run on host via gcloud SSH:"
printf '\n  %s%s\n\n' "$BOLD" "gcloud compute ssh ${GCP_INSTANCE_NAME} --zone=${GCP_ZONE} --command='bash -s' << 'EOS'\n${REMOTE_SETUP_SCRIPT}\nEOS"

if command -v gcloud >/dev/null 2>&1; then
  if confirm "Execute remote display startup via gcloud SSH now?"; then
    say "Connecting to ${GCP_INSTANCE_NAME}..."
    gcloud compute ssh "${GCP_INSTANCE_NAME}" --zone="${GCP_ZONE}" --command="bash -s" << EOS || warn "Could not run command directly via SSH; run it manually on the instance."
${REMOTE_SETUP_SCRIPT}
EOS
  fi
fi

say "Your 3-User Syntropy Environment is Ready:"
say "  • Syntropy Web Console: ${CONSOLE_URL}"
say "  • User 1 Display (:1):   ${USER_1_VNC}"
say "  • User 2 Display (:2):   ${USER_2_VNC}"
say "  • User 3 Display (:3):   ${USER_3_VNC}"

if confirm "Open User 1 display and Web Console in your local browser now?"; then
  open_url "$USER_1_VNC"
  open_url "$CONSOLE_URL"
fi

finish
